# Generated by Django 3.1.4 on 2021-10-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlhash',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='posts.post'),
        ),
    ]
